[project]
name = "Buffet"
version = "0.1.0"
dependencies = [
    "anybadge>=1.16.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-watch>=4.2.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]

[tool.pytest.ini_options]
addopts = "--cov=."
testpaths = ["test"]
